# Generated by Django 6.0.4 on 2026-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='activities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='region',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
