# Generated by Django 6.0.4 on 2026-04-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_region_activities_region_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
