# Generated by Django 6.0.4 on 2026-04-28 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('partners', '0002_partnerprofile_hours_partnerprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_services', to='partners.partnerprofile'),
        ),
    ]
