# Generated by Django 6.0.4 on 2026-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
