# Generated by Django 6.0.4 on 2026-04-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_external_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='external_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
