# Generated by Django 6.0.4 on 2026-04-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerprofile_hours_partnerprofile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
